---
services:
  ai_trading_bot:
    image: ai_trading_botorg/ai_trading_bot:stable
    # image: ai_trading_botorg/ai_trading_bot:develop
    # Use plotting image
    # image: ai_trading_botorg/ai_trading_bot:develop_plot
    # # Enable GPU Image and GPU Resources (only relevant for freqAI)
    # # Make sure to uncomment the whole deploy section
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: ai_trading_bot
    volumes:
      - "./user_data:/ai_trading_bot/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://github.com/MuhammadMuazzain/ai-trading-bot/rest-api/ documentation
    # for more information.
    ports:
      - "127.0.0.1:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /ai_trading_bot/user_data/logs/ai_trading_bot.log
      --db-url sqlite:////ai_trading_bot/user_data/tradesv3.sqlite
      --config /ai_trading_bot/user_data/config.json
      --strategy SampleStrategy
