[build-system]
requires = ["setuptools >= 64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ai-trading-bot-client"
dynamic = ["version"]

authors = [
  {name = "Muhammad Muazzain"},
  {name = "Muhammad Muazzain", email = "muhammadmuazzain07@gmail.com"},
]

description = "AI Trading Bot — REST API client library"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "GPLv3"}
# license = "GPLv3"
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: MacOS",
    "Operating System :: Unix",
    "Topic :: Office/Business :: Financial :: Investment",
]

dependencies = [
  'requests >= 2.26.0',
  'python-rapidjson >= 1.0',
]


[project.urls]
Homepage = "https://github.com/MuhammadMuazzain/ai-trading-bot"
Documentation = "https://github.com/MuhammadMuazzain/ai-trading-bot"
"Bug Tracker" = "https://github.com/MuhammadMuazzain/ai-trading-bot/issues"


[project.scripts]
ai-trading-bot-client = "ai_trading_bot_client.cli:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["ai_trading_bot_client*"]
exclude = ["tests", "tests.*"]
namespaces = true

[tool.setuptools.dynamic]
version = {attr = "ai_trading_bot_client.__version__"}
