FROM python:3.14-slim-bookworm

WORKDIR /app

COPY requirements.txt requirements-freqai.txt requirements-freqai-rl.txt /app/

RUN pip install --upgrade pip \
  && pip install -r requirements.txt --no-cache-dir \
  && pip install -r requirements-freqai.txt --no-cache-dir \
  && pip install -r requirements-freqai-rl.txt --no-cache-dir

COPY . /app/
RUN pip install -e . --no-cache-dir

ENTRYPOINT ["ai-trading-bot"]
