FROM python:3.14-slim-bookworm

WORKDIR /app

COPY requirements.txt requirements-plot.txt /app/

RUN pip install --upgrade pip \
  && pip install -r requirements.txt --no-cache-dir \
  && pip install -r requirements-plot.txt --no-cache-dir \
  && pip install jupyter --no-cache-dir

COPY . /app/
RUN pip install -e . --no-cache-dir

ENTRYPOINT ["jupyter", "notebook", "--ip=0.0.0.0", "--allow-root"]
