FROM python:3.11-slim-bookworm

WORKDIR /app

COPY requirements-dev.txt /app/

RUN pip install --upgrade pip \
  && pip install numpy --no-cache-dir \
  && pip install -r requirements-dev.txt --no-cache-dir

COPY . /app/
RUN pip install -e . --no-cache-dir

ENTRYPOINT []
